language: go

go:
 - 1.5
 - 1.6
 - 1.7
 - tip

services:
  - redis-server

addons:
  rethinkdb: '2.3'

env:
  - GO15VENDOREXPERIMENT=1

install:
 - mkdir -p $GOPATH/bin
 - which glide >/dev/null || curl https://glide.sh/get | sh
 - glide install

script:
 - go test $(go list ./... | grep -v /vendor/)
