language: go

go:
 - 1.5
 - 1.6
 - 1.7
 - tip

services:
  - redis-server

env:
  - GO15VENDOREXPERIMENT=1

script:
 - which glide >/dev/null || curl https://glide.sh/get | sh
 - glide install
 - go test $(go list ./... | grep -v /vendor/)
